//Date  12-01-2022
 public class LuckyNumber {

	public static void main(String args[]){
	
	 double tempNum  = Math.random();
	 
	 int tempNum2  =(int)  (tempNum *100);   //0-99
															//(0-99) +1  = 1 -100
	 int autoGeneratedLuckNumber  = tempNum2 + 1;  //1-100
	 
	 java.util.Scanner scan  = new java.util.Scanner(System.in);
	 System.out.println("which is your luck Number?(1-100)");
	 int userInputNumber=scan.nextInt();
	  
	  if(autoGeneratedLuckNumber==userInputNumber){
	   System.out.println("Winner :: you are lucky..  enjoy life");
	  }else{
	    System.out.println("try again for better luck...");
	  }
	  
	  System.out.println("____________________");
		System.out.println("luck number is  " + autoGeneratedLuckNumber);
	  System.out.println("____________________");
	  
	  
	}//end main

}//end class